services:
  - type: web
    name: bazaarika-chatbot
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true
    
